### Site Settings ###
title               : mafda
description         : >- # this means to ignore new|lines until "baseurl:"
                      <h2>fernanda rodriguez</h2><br>
                      :dart: data scientist. front-end dev.<br>
                      :mortar_board: multimedia engineer<br>
                      :mortar_board: m.sc. in mechanical eng.<br>
                      :construction: ph.d. candidate in augmented reality & machine learning.

keywords: "fernanda rodriguez, maria fernanda rodriguez ruiz, mafda, mafda_, multimedia engineer, computer applications, augmented reality, machine learning, computer graphics, computer vision, image processing, interaction human-computer, digital media, web design, digital image and video, 3D modeling, 3D rendering, 3D animation, jekyll, blog, personal website"
head_description: "iâ€™m fernanda rodriguez, multimedia engineer. data scientist. front-end dev. phd candidate: augmented reality + machine learning."
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : "mafda/mafda.github.io"     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name              : fernanda rodriguez
  image             : https://avatars3.githubusercontent.com/u/7698160
  email             : mafda13@gmail.com
  github            : mafda
  gitlab            : mafda
  linkedin          : mafda
  medium            : mafda
  kaggle            : mafdarr
  codepen           : mafda
  hackerrank        : mafda
  researchgate      : Maria_Rodriguez_Ruiz2
  twitter           : mafda_


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: UA-136851951-1


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
